name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Release
      uses: cycjimmy/semantic-release-action@v3
      with:
        semantic_version: 18.0.0
        extra_plugins: |
          @semantic-release/changelog@6.0.0
          @semantic-release/git@10.0.0
          conventional-changelog-conventionalcommits@4.6.3
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
