name: execute terraform

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.DOCKER_PAT }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Pull Ansiform Docker Image
      run: docker pull ghcr.io/dme86/ansiform:d8c52438841d9e7a4e2c7d46dffb36821b044ea6

    - name: Run Terraform Commands
      run: |
        terraform init && \
        terraform plan && \
        terraform apply -auto-approve
